[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'artifacts/contracts'
libs = ['lib']
no_match_path = "contracts/*"
solc_version = '0.8.18'
optimizer = true
optimizer_runs = 18_000
viaIR = false
eth_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/vevMezCXoFshwV190wQcekYwQflctBeE"

[profile.test]
fork_block_number = 17237181

[profile.ci_sizes]
optimizer_runs = 18_000
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
# temporary workaround while we figure out perf issues + configure different test sets + profiles
runs = 1000
max_test_rejects = 10_000_000
[rpc_endpoints]
sepolia = 'https://mainnet.infura.io/v3/901ff66ce2bd4fa89b01c5fd38f0ccc9'